// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7ttuPGSdE3vpBIP-o3I5q470X8QsUIQ',
    appId: '1:73427321500:web:214b84b63c6940495b6359',
    messagingSenderId: '73427321500',
    projectId: 'vitacare-3c507',
    authDomain: 'vitacare-3c507.firebaseapp.com',
    storageBucket: 'vitacare-3c507.firebasestorage.app',
    measurementId: 'G-S859NZNFL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1XwcCSrlaAuSUUeLsOjlre-sk3i3vPyg',
    appId: '1:73427321500:android:63800ef87136ab685b6359',
    messagingSenderId: '73427321500',
    projectId: 'vitacare-3c507',
    storageBucket: 'vitacare-3c507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHvsKXSxsYgP80Xt6D6LH896jN02fxW0',
    appId: '1:73427321500:ios:68606dea79cd2f625b6359',
    messagingSenderId: '73427321500',
    projectId: 'vitacare-3c507',
    storageBucket: 'vitacare-3c507.firebasestorage.app',
    iosClientId: '73427321500-r9ufdsqjq4lgjk2uffa7ar24kgeajb1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHvsKXSxsYgP80Xt6D6LH896jN02fxW0',
    appId: '1:73427321500:ios:68606dea79cd2f625b6359',
    messagingSenderId: '73427321500',
    projectId: 'vitacare-3c507',
    storageBucket: 'vitacare-3c507.firebasestorage.app',
    iosClientId: '73427321500-r9ufdsqjq4lgjk2uffa7ar24kgeajb1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS7ttuPGSdE3vpBIP-o3I5q470X8QsUIQ',
    appId: '1:73427321500:web:a447467a4ad258e95b6359',
    messagingSenderId: '73427321500',
    projectId: 'vitacare-3c507',
    authDomain: 'vitacare-3c507.firebaseapp.com',
    storageBucket: 'vitacare-3c507.firebasestorage.app',
    measurementId: 'G-XTKP0MLQD8',
  );

}